# General Site Settings
menu :
  - {name: 'Blogs', url: 'blogs'}
  - {name: 'Work',  url: 'work'}
  - {name: 'Books', url: 'books'}
  # - {name: 'Columns',   url: 'columns'}
  - {name: 'Projects', url: 'projects'}
  - {name: 'Journal', url: 'journals'}
  - {name: 'Podcasts', url: 'podcasts'}

column:
  - { name: 'Inequality and Inefficiency', date : 2023-07-16, url: 'columns/inequality-and-inefficiency' } 
  - { name: 'Hola Niño', date : 2023-07-19, url:  'columns/hola-niño' }
  - { name: 'Rice Up', date : 2023-08-28, url:  'columns/rice-up' }
  - { name: 'Disputes', date : 2023-10-10, url:  'columns/disputes' }

books:
  - { name: 'Currently Working', description : 'This is where I post the books that I am currently writing', url:  'books/ongoing' }
  - { name: 'Published Books', description : 'The books that I''ve published are written here' , url: 'books/published' } 
  - { name: 'My Reads', description : 'The books that inspire me to write and live.', url:  'books/reads' }

# Work Section

work:
  - {name: 'Sales and Marketing',  description : 'Look at my work on how I became good in sales.',  url: 'work/sales'}
  - {name: 'Music', description : 'Where I published my written songs and whole other work in music. ',  url: 'work/music'}
  - {name: 'Podcast Editing', description : 'Look at my work on how I became good in sales.',  url: 'work/podcasts'}
#-------------------------------


sales:
  - { name: 'Cold Calling',  description : 'I compiled all my recorded cold calls in here, so check them out.',  url: 'work/sales/cold-calling'}
  - { name: 'Sales Techniques', description : 'Where I published my written songs and whole other work in music. ',  url: 'work/sales/techniques'}
  - { name: 'CRM Tools', description : 'Look at my work on how I became good in sales.',  url: 'work/podcasts'}
  - { name: 'Productivity Tools', description : 'Look at my work on how I became good in sales.',  url: 'work/podcasts'}
  - { name: 'Blogs', description : 'Look at my work on how I became good in sales.',  url: 'work/podcasts'}
#-------------------------------


# Contact Section

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal Website for Abr Da Great'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-144656396-1'

#-------------------------------
# Disqus Section
# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: ''
